defmodule LaboratoriesTest do
  use ExUnit.Case

  describe "Laboratories.run/1" do
    test "returns the total number of beam splits" do
      assert Laboratories.run("""
             .......S.......
             ...............
             .......^.......
             ...............
             ......^.^......
             ...............
             .....^.^.^.....
             ...............
             ....^.^...^....
             ...............
             ...^.^...^.^...
             ...............
             ..^...^.....^..
             ...............
             .^.^.^.^.^...^.
             ...............
             """) == 21
    end
  end
end
